site_name: team-geek-dream
site_description: "Main documentation for team-geek-dream project"
repo_url: https://github.com/xgeeks-geekathon/team-geek-dream.git
edit_uri: edit/master/docs

# plugins:
#   - techdocs-core

# For sidebar navigation
nav:
  - Getting Started: "index.md"
